# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Mosaic.py
# Created on: 2014-12-10 15:30:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
v2327NE_ecw = "E:\\ImageFolder\\2327NE.ecw"
Imagery2014_DBO_T2327NE = "Database Connections\\sa@Imagery2014.sde\\Imagery2014.DBO.T2327NE"

# Process: Mosaic
arcpy.Mosaic_management("E:\\ImageFolder\\2327NE.ecw", Imagery2014_DBO_T2327NE, "LAST", "FIRST", "", "", "NONE", "0", "NONE")

def MosaicImages(filePath, target):
    try:

        arcpy.Mosaic_management(filePath, target,  "LAST", "FIRST", "", "", "NONE", "0", "NONE")

    except Exception as inst:
        ST = CommonTasks.ScheduledTask(layerFolder,inst,LogFile,arcpy.GetMessages())
        ST.SendErrorMail()
        ST.UpdateLogFile()